/**
 * This is a map of android devices' timezones 
 * to convert to moment's timezone format.
 */
DateTools.ANDROID_TO_MOMENT_TIMEZONE_MAP = {
  "MIT": "Pacific/Apia",
  "America/Adak": "America/Adak",
  "HST": "Pacific/Fakaofo",
  "Pacific/Marquesas": "Pacific/Marquesas",
  "AST": "America/Juneau",
  "Pacific/Gambier": "Pacific/Gambier",
  "PST": "America/Los_Angeles",
  "Pacific/Pitcairn": "Pacific/Pitcairn",
  "MST": "America/Denver",
  "MST7": "America/Phoenix",
  "CST": "America/Chicago",
  "America/Belize": "America/Guatemala",
  "EST5": "America/Lima",
  "EST": "America/New_York",
  "PRT": "America/Guyana",
  "America/Asuncion": "America/Asuncion",
  "America/Cuiaba": "America/Cuiaba",
  "America/Goose_Bay": "America/Goose_Bay",
  "America/Santiago": "America/Santiago",
  "America/Glace_Bay": "America/Halifax",
  "CNT": "America/St_Johns",
  "America/Araguaina": "America/Sao_Paulo",
  "AGT": "America/Montevideo",
  "America/Godthab": "America/Godthab",
  "America/Noronha": "Atlantic/South_Georgia",
  "America/Scoresbysund": "Atlantic/Azores",
  "Atlantic/Cape_Verde": "Atlantic/Cape_Verde",
  "GMT": "Europe/London",
  "WET": "Europe/Lisbon",
  "Africa/Algiers": "Africa/Algiers",
  "CET": "Europe/Berlin",
  "ART": "Africa/Cairo",
  "CAT": "Africa/Johannesburg",
  "Asia/Jerusalem": "Asia/Jerusalem",
  "EET": "Europe/Athens",
  "Europe/Kaliningrad": "Europe/Minsk",
  "Asia/Baghdad": "Asia/Baghdad",
  "Europe/Moscow": "Europe/Moscow",
  "EAT": "Africa/Nairobi",
  "Asia/Tehran": "Asia/Tehran",
  "Asia/Baku": "Asia/Baku",
  "Asia/Aqtau":"Asia/Tbilisi",
  "Asia/Yerevan": "Asia/Yerevan",
  "NET": "Asia/Muscat",
  "Asia/Kabul": "Asia/Kabul",
  "Asia/Yekaterinburg": "Asia/Yekaterinburg",
  "PLT": "Asia/Karachi",
  "BST": "Asia/Colombo",
  "Asia/Almaty": "Asia/Almaty",
  "Asia/Novosibirsk": "Asia/Novosibirsk",
  "Asia/Rangoon": "Asia/Rangoon",
  "VST": "Asia/Jakarta",
  "Asia/Krasnoyarsk": "Asia/Krasnoyarsk",
  "CTT": "Asia/Hong_Kong",
  "Asia/Irkutsk": "Asia/Irkutsk",
  "JST": "Asia/Tokyo",
  "Asia/Yakutsk": "Asia/Yakutsk",
  "Australia/Adelaide": "Australia/Adelaide",
  "ACT": "Australia/Darwin",
  "Antarctica/DumontDUrville": "Australia/Brisbane",
  "Asia/Vladivostok": "Asia/Vladivostok",
  "Australia/Hobart": "Australia/Hobart",
  "AET": "Australia/Melbourne"
};
